# pyproject.toml file for Black settings
[tool.black]
line-length = 120
target-version = ['py310', 'py311', 'py312', 'py313']
include = '\.pyi?$'
# check later: https://github.com/psf/black/blob/main/docs/guides/using_black_with_other_tools.md
